/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login_Signup;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author vimle
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_Panel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        L_background = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        or = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        head = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        u_sep = new javax.swing.JSeparator();
        p_sep = new javax.swing.JSeparator();
        password = new javax.swing.JPasswordField();
        password_label = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        setResizable(false);
        setSize(new java.awt.Dimension(744, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Signup/book.png"))); // NOI18N
        L_Panel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 70, 70));

        L_background.setBackground(new java.awt.Color(123, 14, 123));
        L_background.setOpaque(true);
        L_Panel.add(L_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 510));

        getContentPane().add(L_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 510));

        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        or.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        or.setForeground(new java.awt.Color(123, 14, 123));
        or.setText("or");
        Login.add(or, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        jButton1.setForeground(new java.awt.Color(123, 14, 123));
        jButton1.setText("Register Now");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(123, 14, 123), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Login.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 100, 30));

        head.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        head.setForeground(new java.awt.Color(123, 14, 123));
        head.setText("Login");
        Login.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 140, 50));

        username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        username.setBorder(null);
        Login.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 240, 40));

        Submit.setBackground(new java.awt.Color(255, 255, 255));
        Submit.setForeground(new java.awt.Color(123, 14, 123));
        Submit.setText("Submit");
        Submit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(123, 14, 123), 1, true));
        Submit.setContentAreaFilled(false);
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        Login.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 100, 30));

        u_sep.setForeground(new java.awt.Color(0, 0, 0));
        Login.add(u_sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 240, 10));

        p_sep.setForeground(new java.awt.Color(0, 0, 0));
        Login.add(p_sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 240, 10));

        password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        Login.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 240, 40));

        password_label.setLabelFor(password);
        password_label.setText("Password");
        Login.add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 140, 30));

        username_label.setLabelFor(username);
        username_label.setText("Username");
        Login.add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 130, 30));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setToolTipText("");
        background.setOpaque(true);
        Login.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 510));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 380, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("1");
        L_Panel.removeAll();
        L_Panel.add(Register);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel L_Panel;
    private javax.swing.JLabel L_background;
    private javax.swing.JPanel Login;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel background;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel or;
    private javax.swing.JSeparator p_sep;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password_label;
    private javax.swing.JSeparator u_sep;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
