/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login_Signup;

/**
 *
 * @author vimle
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_Panel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        L_background = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        head = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        p_sep = new javax.swing.JSeparator();
        password_label = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        username_label3 = new javax.swing.JLabel();
        p_sep1 = new javax.swing.JSeparator();
        p_sep2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Signup/book.png"))); // NOI18N
        L_Panel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 70, 70));

        L_background.setBackground(new java.awt.Color(123, 14, 123));
        L_background.setOpaque(true);
        L_Panel.add(L_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 510));

        getContentPane().add(L_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 510));

        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        head.setForeground(new java.awt.Color(123, 14, 123));
        head.setText("Sign Up");
        Login.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 140, 50));

        Submit.setBackground(new java.awt.Color(255, 255, 255));
        Submit.setForeground(new java.awt.Color(123, 14, 123));
        Submit.setText("Sign Up");
        Submit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(123, 14, 123), 1, true));
        Submit.setContentAreaFilled(false);
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        Login.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 100, 30));

        p_sep.setForeground(new java.awt.Color(0, 0, 0));
        Login.add(p_sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 240, 10));

        password_label.setText("Re-enter Password");
        Login.add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 140, 30));

        username_label.setText("Password");
        Login.add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 130, 30));

        username_label3.setText("Roll Number");
        Login.add(username_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 130, 30));

        p_sep1.setForeground(new java.awt.Color(0, 0, 0));
        Login.add(p_sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 240, 30));

        p_sep2.setForeground(new java.awt.Color(0, 0, 0));
        Login.add(p_sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 240, 10));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 380, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel L_Panel;
    private javax.swing.JLabel L_background;
    private javax.swing.JPanel Login;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel head;
    private javax.swing.JLabel logo;
    private javax.swing.JSeparator p_sep;
    private javax.swing.JSeparator p_sep1;
    private javax.swing.JSeparator p_sep2;
    private javax.swing.JLabel password_label;
    private javax.swing.JLabel username_label;
    private javax.swing.JLabel username_label3;
    // End of variables declaration//GEN-END:variables
}
