/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;



import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author vimle
 */
public class home extends javax.swing.JFrame {
    
    /**
     * Creates new form dashboard
     * @param username
     */
    public home(String username) {
        initComponents();
        name1.setText(username);
        //name2.setText(username);
    }

    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_menu = new javax.swing.JPanel();
        manage_books = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        return_book = new javax.swing.JButton();
        search_book = new javax.swing.JButton();
        issue_book = new javax.swing.JButton();
        issued_book = new javax.swing.JButton();
        about = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        icon2 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();
        manage = new javax.swing.JPanel();
        IssueBook = new javax.swing.JPanel();
        IssuedBook = new javax.swing.JPanel();
        ReturnBook = new javax.swing.JPanel();
        about_p = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SearchBook = new javax.swing.JPanel();
        Profile = new javax.swing.JPanel();
        home_card = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_menu.setBackground(new java.awt.Color(255, 255, 255));
        side_menu.setAutoscrolls(true);
        side_menu.setFocusable(false);
        side_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manage_books.setBackground(new java.awt.Color(255, 255, 255));
        manage_books.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        manage_books.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/Manage Books.png"))); // NOI18N
        manage_books.setText("Manage Books");
        manage_books.setBorderPainted(false);
        manage_books.setContentAreaFilled(false);
        manage_books.setFocusPainted(false);
        manage_books.setHideActionText(true);
        manage_books.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manage_books.setIconTextGap(15);
        manage_books.setMaximumSize(new java.awt.Dimension(200, 50));
        manage_books.setMinimumSize(new java.awt.Dimension(200, 50));
        manage_books.setOpaque(true);
        manage_books.setPreferredSize(new java.awt.Dimension(210, 40));
        manage_books.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                manage_booksFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                manage_booksFocusLost(evt);
            }
        });
        manage_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_booksActionPerformed(evt);
            }
        });
        side_menu.add(manage_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 50));

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/profile.png"))); // NOI18N
        profile.setText("Profile");
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        profile.setFocusPainted(false);
        profile.setHideActionText(true);
        profile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profile.setIconTextGap(15);
        profile.setMaximumSize(new java.awt.Dimension(200, 50));
        profile.setMinimumSize(new java.awt.Dimension(200, 50));
        profile.setOpaque(true);
        profile.setPreferredSize(new java.awt.Dimension(210, 40));
        profile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                profileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                profileFocusLost(evt);
            }
        });
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        side_menu.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 50));

        return_book.setBackground(new java.awt.Color(255, 255, 255));
        return_book.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        return_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/Return book.png"))); // NOI18N
        return_book.setText("Return Book");
        return_book.setBorderPainted(false);
        return_book.setContentAreaFilled(false);
        return_book.setFocusPainted(false);
        return_book.setHideActionText(true);
        return_book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        return_book.setIconTextGap(15);
        return_book.setMaximumSize(new java.awt.Dimension(200, 50));
        return_book.setMinimumSize(new java.awt.Dimension(200, 50));
        return_book.setOpaque(true);
        return_book.setPreferredSize(new java.awt.Dimension(210, 40));
        return_book.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                return_bookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                return_bookFocusLost(evt);
            }
        });
        return_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_bookActionPerformed(evt);
            }
        });
        side_menu.add(return_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, 50));

        search_book.setBackground(new java.awt.Color(255, 255, 255));
        search_book.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        search_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/search book.png"))); // NOI18N
        search_book.setText("Search Book");
        search_book.setBorderPainted(false);
        search_book.setContentAreaFilled(false);
        search_book.setFocusPainted(false);
        search_book.setHideActionText(true);
        search_book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        search_book.setIconTextGap(15);
        search_book.setMaximumSize(new java.awt.Dimension(200, 50));
        search_book.setMinimumSize(new java.awt.Dimension(200, 50));
        search_book.setOpaque(true);
        search_book.setPreferredSize(new java.awt.Dimension(210, 40));
        search_book.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_bookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search_bookFocusLost(evt);
            }
        });
        search_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_bookActionPerformed(evt);
            }
        });
        side_menu.add(search_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 50));

        issue_book.setBackground(new java.awt.Color(255, 255, 255));
        issue_book.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        issue_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/issue book.png"))); // NOI18N
        issue_book.setText("Issue Books");
        issue_book.setBorderPainted(false);
        issue_book.setContentAreaFilled(false);
        issue_book.setFocusPainted(false);
        issue_book.setHideActionText(true);
        issue_book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        issue_book.setIconTextGap(15);
        issue_book.setMaximumSize(new java.awt.Dimension(200, 50));
        issue_book.setMinimumSize(new java.awt.Dimension(200, 50));
        issue_book.setOpaque(true);
        issue_book.setPreferredSize(new java.awt.Dimension(210, 40));
        issue_book.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                issue_bookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                issue_bookFocusLost(evt);
            }
        });
        issue_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue_bookActionPerformed(evt);
            }
        });
        side_menu.add(issue_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 50));

        issued_book.setBackground(new java.awt.Color(255, 255, 255));
        issued_book.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        issued_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/issued books.png"))); // NOI18N
        issued_book.setText("Issued Books");
        issued_book.setBorderPainted(false);
        issued_book.setContentAreaFilled(false);
        issued_book.setFocusPainted(false);
        issued_book.setHideActionText(true);
        issued_book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        issued_book.setIconTextGap(15);
        issued_book.setMaximumSize(new java.awt.Dimension(200, 50));
        issued_book.setMinimumSize(new java.awt.Dimension(200, 50));
        issued_book.setOpaque(true);
        issued_book.setPreferredSize(new java.awt.Dimension(210, 40));
        issued_book.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                issued_bookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                issued_bookFocusLost(evt);
            }
        });
        issued_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issued_bookActionPerformed(evt);
            }
        });
        side_menu.add(issued_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, 50));

        about.setBackground(new java.awt.Color(255, 255, 255));
        about.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/about.png"))); // NOI18N
        about.setText("About");
        about.setBorderPainted(false);
        about.setContentAreaFilled(false);
        about.setFocusPainted(false);
        about.setHideActionText(true);
        about.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        about.setIconTextGap(15);
        about.setMaximumSize(new java.awt.Dimension(200, 50));
        about.setMinimumSize(new java.awt.Dimension(200, 50));
        about.setOpaque(true);
        about.setPreferredSize(new java.awt.Dimension(210, 40));
        about.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aboutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aboutFocusLost(evt);
            }
        });
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        side_menu.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 200, 50));

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/home.png"))); // NOI18N
        Home.setText("Home");
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.setFocusPainted(false);
        Home.setHideActionText(true);
        Home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home.setIconTextGap(15);
        Home.setMaximumSize(new java.awt.Dimension(200, 50));
        Home.setMinimumSize(new java.awt.Dimension(200, 50));
        Home.setOpaque(true);
        Home.setPreferredSize(new java.awt.Dimension(210, 40));
        Home.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                HomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                HomeFocusLost(evt);
            }
        });
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        side_menu.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 50));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 80));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/user_lx.png"))); // NOI18N
        jPanel3.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 65, -1));

        name1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name1.setText("Vimlesh Kumar");
        jPanel3.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 22, 97, -1));

        side_menu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 80));

        getContentPane().add(side_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 640));

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout manageLayout = new javax.swing.GroupLayout(manage);
        manage.setLayout(manageLayout);
        manageLayout.setHorizontalGroup(
            manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        manageLayout.setVerticalGroup(
            manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        main_panel.add(manage, "card5");

        javax.swing.GroupLayout IssueBookLayout = new javax.swing.GroupLayout(IssueBook);
        IssueBook.setLayout(IssueBookLayout);
        IssueBookLayout.setHorizontalGroup(
            IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        IssueBookLayout.setVerticalGroup(
            IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        main_panel.add(IssueBook, "card4");

        javax.swing.GroupLayout IssuedBookLayout = new javax.swing.GroupLayout(IssuedBook);
        IssuedBook.setLayout(IssuedBookLayout);
        IssuedBookLayout.setHorizontalGroup(
            IssuedBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        IssuedBookLayout.setVerticalGroup(
            IssuedBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        main_panel.add(IssuedBook, "card3");

        javax.swing.GroupLayout ReturnBookLayout = new javax.swing.GroupLayout(ReturnBook);
        ReturnBook.setLayout(ReturnBookLayout);
        ReturnBookLayout.setHorizontalGroup(
            ReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        ReturnBookLayout.setVerticalGroup(
            ReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        main_panel.add(ReturnBook, "card2");

        about_p.setBackground(new java.awt.Color(255, 255, 255));
        about_p.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Library Management ");
        about_p.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("System");
        about_p.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Developed By:");
        about_p.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel5.setText("Vimlesh Kumar");
        about_p.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 130, -1));

        jLabel6.setText("Umesh Maharwaha");
        about_p.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel7.setText("Sakshi Bassi");
        about_p.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLabel8.setText("Navreet Kaur");
        about_p.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Beta version");
        about_p.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, 20));

        main_panel.add(about_p, "about");

        javax.swing.GroupLayout SearchBookLayout = new javax.swing.GroupLayout(SearchBook);
        SearchBook.setLayout(SearchBookLayout);
        SearchBookLayout.setHorizontalGroup(
            SearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        SearchBookLayout.setVerticalGroup(
            SearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        main_panel.add(SearchBook, "card4");

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        main_panel.add(Profile, "card4");

        home_card.setBackground(new java.awt.Color(255, 255, 255));
        home_card.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Book Issued:");
        home_card.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel15.setText("500");
        home_card.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 90, 60));
        home_card.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 150, 100));
        home_card.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 150, 100));

        jLabel13.setBackground(new java.awt.Color(255, 102, 255));
        jLabel13.setForeground(new java.awt.Color(255, 102, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\vimle\\Desktop\\Backgnd1.jpg")); // NOI18N
        home_card.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 600));

        jLabel10.setText("Book Dues:");
        home_card.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        main_panel.add(home_card, "profile");
        home_card.getAccessibleContext().setAccessibleName("profile_p");

        getContentPane().add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 890, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 153, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(1030, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(1030, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Librarian Panel");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setRequestFocusEnabled(false);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 890, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    final Color theme = new Color(255,204,102);
    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        main_panel.removeAll();
        main_panel.add(home_card);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_HomeActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void HomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HomeFocusGained
        Home.setBackground(theme);
    }//GEN-LAST:event_HomeFocusGained

    private void HomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HomeFocusLost
        Home.setBackground(Color.white);
    }//GEN-LAST:event_HomeFocusLost

    private void profileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_profileFocusGained
        profile.setBackground(theme);
    }//GEN-LAST:event_profileFocusGained

    private void profileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_profileFocusLost
        profile.setBackground(Color.white);
    }//GEN-LAST:event_profileFocusLost

    private void manage_booksFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manage_booksFocusGained
        manage_books.setBackground(theme);
    }//GEN-LAST:event_manage_booksFocusGained

    private void search_bookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_bookFocusLost
        search_book.setBackground(Color.white);
    }//GEN-LAST:event_search_bookFocusLost

    private void manage_booksFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manage_booksFocusLost
        manage_books.setBackground(Color.white);
    }//GEN-LAST:event_manage_booksFocusLost

    private void return_bookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_return_bookFocusGained
        return_book.setBackground(theme);
    }//GEN-LAST:event_return_bookFocusGained

    private void issue_bookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issue_bookFocusGained
        issue_book.setBackground(theme);
    }//GEN-LAST:event_issue_bookFocusGained

    private void issued_bookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issued_bookFocusGained
        issued_book.setBackground(theme);
    }//GEN-LAST:event_issued_bookFocusGained

    private void aboutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aboutFocusGained
        about.setBackground(theme);
    }//GEN-LAST:event_aboutFocusGained

    private void issued_bookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issued_bookFocusLost
        issued_book.setBackground(Color.white);
    }//GEN-LAST:event_issued_bookFocusLost

    private void aboutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aboutFocusLost
        about.setBackground(Color.white);
    }//GEN-LAST:event_aboutFocusLost

    private void issue_bookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issue_bookFocusLost
        issue_book.setBackground(Color.white);
    }//GEN-LAST:event_issue_bookFocusLost

    private void return_bookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_return_bookFocusLost
        return_book.setBackground(Color.white);
    }//GEN-LAST:event_return_bookFocusLost

    private void search_bookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_bookFocusGained
        search_book.setBackground(theme);
    }//GEN-LAST:event_search_bookFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        main_panel.removeAll();
        main_panel.add(Profile);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        main_panel.removeAll();
        main_panel.add(about_p);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_aboutActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        main_panel.removeAll();
        main_panel.add(Profile);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_profileActionPerformed

    private void manage_booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_booksActionPerformed
        main_panel.removeAll();
        main_panel.add(manage);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_manage_booksActionPerformed

    private void search_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bookActionPerformed
        main_panel.removeAll();
        main_panel.add(SearchBook);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_search_bookActionPerformed

    private void return_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_bookActionPerformed
        main_panel.removeAll();
        main_panel.add(ReturnBook);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_return_bookActionPerformed

    private void issue_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue_bookActionPerformed
        main_panel.removeAll();
        main_panel.add(IssueBook);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_issue_bookActionPerformed

    private void issued_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issued_bookActionPerformed
        main_panel.removeAll();
        main_panel.add(IssuedBook);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_issued_bookActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton Home;
    private javax.swing.JPanel IssueBook;
    private javax.swing.JPanel IssuedBook;
    private javax.swing.JPanel Profile;
    private javax.swing.JPanel ReturnBook;
    private javax.swing.JPanel SearchBook;
    private javax.swing.JButton about;
    private javax.swing.JPanel about_p;
    private javax.swing.JPanel home_card;
    private javax.swing.JLabel icon2;
    private javax.swing.JButton issue_book;
    private javax.swing.JButton issued_book;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel manage;
    private javax.swing.JButton manage_books;
    private javax.swing.JLabel name1;
    private javax.swing.JButton profile;
    private javax.swing.JButton return_book;
    private javax.swing.JButton search_book;
    private javax.swing.JPanel side_menu;
    // End of variables declaration//GEN-END:variables
}
