/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;



import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author vimle
 */
public class home extends javax.swing.JFrame {
    
    /**
     * Creates new form dashboard
     * @param username
     */
    public home(String username) {
        initComponents();
        name1.setText(username);
        //name2.setText(username);
        
    }

    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_menu = new javax.swing.JPanel();
        manage_books = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        return_book = new javax.swing.JButton();
        search_book = new javax.swing.JButton();
        issue_book = new javax.swing.JButton();
        issued_book = new javax.swing.JButton();
        about = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        icon2 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();
        manage = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        IssueBook = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        IssuedBook = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        ReturnBook = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        about_p = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SearchBook = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Profile = new javax.swing.JPanel();
        home_card = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setIconImage(new ImageIcon(getClass().getResource("/Login_Signup/logo.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_menu.setBackground(new java.awt.Color(255, 255, 255));
        side_menu.setAutoscrolls(true);
        side_menu.setFocusable(false);
        side_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manage_books.setBackground(new java.awt.Color(255, 255, 255));
        manage_books.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        manage_books.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/Manage Books.png"))); // NOI18N
        manage_books.setText("Manage Books");
        manage_books.setBorderPainted(false);
        manage_books.setContentAreaFilled(false);
        manage_books.setFocusPainted(false);
        manage_books.setHideActionText(true);
        manage_books.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manage_books.setIconTextGap(15);
        manage_books.setMaximumSize(new java.awt.Dimension(200, 50));
        manage_books.setMinimumSize(new java.awt.Dimension(200, 50));
        manage_books.setOpaque(true);
        manage_books.setPreferredSize(new java.awt.Dimension(210, 40));
        manage_books.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                manage_booksFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                manage_booksFocusLost(evt);
            }
        });
        manage_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_booksActionPerformed(evt);
            }
        });
        side_menu.add(manage_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 50));

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/profile.png"))); // NOI18N
        profile.setText("Profile");
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        profile.setFocusPainted(false);
        profile.setHideActionText(true);
        profile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profile.setIconTextGap(15);
        profile.setMaximumSize(new java.awt.Dimension(200, 50));
        profile.setMinimumSize(new java.awt.Dimension(200, 50));
        profile.setOpaque(true);
        profile.setPreferredSize(new java.awt.Dimension(210, 40));
        profile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                profileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                profileFocusLost(evt);
            }
        });
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        side_menu.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 50));

        return_book.setBackground(new java.awt.Color(255, 255, 255));
        return_book.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        return_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/Return book.png"))); // NOI18N
        return_book.setText("Return Book");
        return_book.setBorderPainted(false);
        return_book.setContentAreaFilled(false);
        return_book.setFocusPainted(false);
        return_book.setHideActionText(true);
        return_book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        return_book.setIconTextGap(15);
        return_book.setMaximumSize(new java.awt.Dimension(200, 50));
        return_book.setMinimumSize(new java.awt.Dimension(200, 50));
        return_book.setOpaque(true);
        return_book.setPreferredSize(new java.awt.Dimension(210, 40));
        return_book.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                return_bookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                return_bookFocusLost(evt);
            }
        });
        return_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_bookActionPerformed(evt);
            }
        });
        side_menu.add(return_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, 50));

        search_book.setBackground(new java.awt.Color(255, 255, 255));
        search_book.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        search_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/search book.png"))); // NOI18N
        search_book.setText("Search Book");
        search_book.setBorderPainted(false);
        search_book.setContentAreaFilled(false);
        search_book.setFocusPainted(false);
        search_book.setHideActionText(true);
        search_book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        search_book.setIconTextGap(15);
        search_book.setMaximumSize(new java.awt.Dimension(200, 50));
        search_book.setMinimumSize(new java.awt.Dimension(200, 50));
        search_book.setOpaque(true);
        search_book.setPreferredSize(new java.awt.Dimension(210, 40));
        search_book.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_bookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search_bookFocusLost(evt);
            }
        });
        search_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_bookActionPerformed(evt);
            }
        });
        side_menu.add(search_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 50));

        issue_book.setBackground(new java.awt.Color(255, 255, 255));
        issue_book.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        issue_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/issue book.png"))); // NOI18N
        issue_book.setText("Issue Books");
        issue_book.setBorderPainted(false);
        issue_book.setContentAreaFilled(false);
        issue_book.setFocusPainted(false);
        issue_book.setHideActionText(true);
        issue_book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        issue_book.setIconTextGap(15);
        issue_book.setMaximumSize(new java.awt.Dimension(200, 50));
        issue_book.setMinimumSize(new java.awt.Dimension(200, 50));
        issue_book.setOpaque(true);
        issue_book.setPreferredSize(new java.awt.Dimension(210, 40));
        issue_book.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                issue_bookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                issue_bookFocusLost(evt);
            }
        });
        issue_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue_bookActionPerformed(evt);
            }
        });
        side_menu.add(issue_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 50));

        issued_book.setBackground(new java.awt.Color(255, 255, 255));
        issued_book.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        issued_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/issued books.png"))); // NOI18N
        issued_book.setText("Issued Books");
        issued_book.setBorderPainted(false);
        issued_book.setContentAreaFilled(false);
        issued_book.setFocusPainted(false);
        issued_book.setHideActionText(true);
        issued_book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        issued_book.setIconTextGap(15);
        issued_book.setMaximumSize(new java.awt.Dimension(200, 50));
        issued_book.setMinimumSize(new java.awt.Dimension(200, 50));
        issued_book.setOpaque(true);
        issued_book.setPreferredSize(new java.awt.Dimension(210, 40));
        issued_book.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                issued_bookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                issued_bookFocusLost(evt);
            }
        });
        issued_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issued_bookActionPerformed(evt);
            }
        });
        side_menu.add(issued_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, 50));

        about.setBackground(new java.awt.Color(255, 255, 255));
        about.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/about.png"))); // NOI18N
        about.setText("About");
        about.setBorderPainted(false);
        about.setContentAreaFilled(false);
        about.setFocusPainted(false);
        about.setHideActionText(true);
        about.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        about.setIconTextGap(15);
        about.setMaximumSize(new java.awt.Dimension(200, 50));
        about.setMinimumSize(new java.awt.Dimension(200, 50));
        about.setOpaque(true);
        about.setPreferredSize(new java.awt.Dimension(210, 40));
        about.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aboutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aboutFocusLost(evt);
            }
        });
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        side_menu.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 200, 50));

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/home.png"))); // NOI18N
        Home.setText("Home");
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.setFocusPainted(false);
        Home.setHideActionText(true);
        Home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home.setIconTextGap(15);
        Home.setMaximumSize(new java.awt.Dimension(200, 50));
        Home.setMinimumSize(new java.awt.Dimension(200, 50));
        Home.setOpaque(true);
        Home.setPreferredSize(new java.awt.Dimension(210, 40));
        Home.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                HomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                HomeFocusLost(evt);
            }
        });
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        side_menu.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 50));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 80));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/user_lx.png"))); // NOI18N
        jPanel3.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 65, -1));

        name1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name1.setText("Vimlesh Kumar");
        jPanel3.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 22, 97, -1));

        side_menu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 80));

        getContentPane().add(side_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 640));

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new java.awt.CardLayout());

        jLabel19.setText("Return Date:");

        jLabel20.setText("Issue Date:");

        jLabel21.setText("Issuer Roll no.:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton6.setText("Save");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel22.setText("Issue Book");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel23.setText("Book Name:");

        jLabel24.setText("Issuer Name:");

        jLabel25.setText("Book ID:");

        javax.swing.GroupLayout manageLayout = new javax.swing.GroupLayout(manage);
        manage.setLayout(manageLayout);
        manageLayout.setHorizontalGroup(
            manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageLayout.createSequentialGroup()
                        .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(manageLayout.createSequentialGroup()
                        .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel21))
                        .addGap(38, 38, 38)
                        .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jTextField5)
                            .addComponent(jTextField8)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField7)
                            .addComponent(jTextField4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageLayout.createSequentialGroup()
                .addGap(0, 608, Short.MAX_VALUE)
                .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(230, 230, 230))))
        );
        manageLayout.setVerticalGroup(
            manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jButton4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        main_panel.add(manage, "card5");

        jLabel26.setText("Issue Book");

        jLabel27.setText("Issuer Name:");

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel28.setText("Return Date:");

        jLabel29.setText("Book Name:");

        jLabel30.setText("Issue Date:");

        jButton9.setText("Save");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jLabel31.setText("Issuer Roll no.:");

        jLabel32.setText("Book ID:");

        javax.swing.GroupLayout IssueBookLayout = new javax.swing.GroupLayout(IssueBook);
        IssueBook.setLayout(IssueBookLayout);
        IssueBookLayout.setHorizontalGroup(
            IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IssueBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IssueBookLayout.createSequentialGroup()
                        .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel30)
                            .addComponent(jLabel28))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(IssueBookLayout.createSequentialGroup()
                        .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31))
                        .addGap(38, 38, 38)
                        .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jTextField14)
                            .addComponent(jTextField13)
                            .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField11)
                            .addComponent(jTextField12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IssueBookLayout.createSequentialGroup()
                .addGap(0, 608, Short.MAX_VALUE)
                .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IssueBookLayout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IssueBookLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(230, 230, 230))))
        );
        IssueBookLayout.setVerticalGroup(
            IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IssueBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jButton8)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(IssueBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        main_panel.add(IssueBook, "card4");

        IssuedBook.setBackground(new java.awt.Color(255, 255, 255));
        IssuedBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book Id", "Student Id", "Issue Date", "Return Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setOpaque(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        IssuedBook.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 820, 520));

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("Issued Books");
        IssuedBook.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/go.png"))); // NOI18N
        jButton11.setContentAreaFilled(false);
        jButton11.setOpaque(true);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        IssuedBook.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, 40));

        main_panel.add(IssuedBook, "card3");

        ReturnBook.setBackground(new java.awt.Color(255, 255, 255));
        ReturnBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setText(" Return a Book ");
        ReturnBook.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setText("Book Id");
        ReturnBook.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("Borrower");
        ReturnBook.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 80, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("Borrower Id");
        ReturnBook.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 100, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setText("Due Date");
        ReturnBook.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setText("Fine");
        ReturnBook.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jTextField17.setBackground(new java.awt.Color(255,255,255,0));
        jTextField17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ReturnBook.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 202, -1));

        jTextField18.setBackground(new java.awt.Color(255,255,255,0));
        jTextField18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ReturnBook.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 202, -1));

        jTextField19.setBackground(new java.awt.Color(255,255,255,0));
        jTextField19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        ReturnBook.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 202, -1));

        jTextField20.setBackground(new java.awt.Color(255,255,255,0));
        jTextField20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        ReturnBook.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 202, -1));

        jTextField21.setBackground(new java.awt.Color(255,255,255,0));
        jTextField21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        ReturnBook.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 202, -1));

        jButton10.setBackground(new java.awt.Color(255, 153, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("Return");
        jButton10.setActionCommand("Borrow");
        jButton10.setBorder(null);
        jButton10.setContentAreaFilled(false);
        jButton10.setOpaque(true);
        ReturnBook.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 120, 40));

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\vimle\\Desktop\\sexy1.png")); // NOI18N
        ReturnBook.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 520, 520));

        main_panel.add(ReturnBook, "card2");

        about_p.setBackground(new java.awt.Color(255, 255, 255));
        about_p.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Library Management ");
        about_p.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("System");
        about_p.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Developed By:");
        about_p.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel5.setText("Vimlesh Kumar");
        about_p.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 130, -1));

        jLabel6.setText("Umesh Maharwaha");
        about_p.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel7.setText("Sakshi Bassi");
        about_p.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLabel8.setText("Navreet Kaur");
        about_p.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Beta version");
        about_p.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, 20));

        main_panel.add(about_p, "about");

        jLabel16.setBackground(new java.awt.Color(153, 255, 153));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Book Name");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 153));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Author Name");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Publisher");

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Clear");

        javax.swing.GroupLayout SearchBookLayout = new javax.swing.GroupLayout(SearchBook);
        SearchBook.setLayout(SearchBookLayout);
        SearchBookLayout.setHorizontalGroup(
            SearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBookLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(SearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(SearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchBookLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchBookLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchBookLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        SearchBookLayout.setVerticalGroup(
            SearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBookLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(SearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(SearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(SearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        main_panel.add(SearchBook, "card4");

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        main_panel.add(Profile, "card4");

        home_card.setBackground(new java.awt.Color(255, 255, 255));
        home_card.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Book Issued:");
        home_card.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel15.setText("500");
        home_card.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 90, 60));
        home_card.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 150, 100));
        home_card.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 150, 100));

        jLabel13.setBackground(new java.awt.Color(255, 102, 255));
        jLabel13.setForeground(new java.awt.Color(255, 102, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\vimle\\Desktop\\Backgnd1.jpg")); // NOI18N
        home_card.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 600));

        jLabel10.setText("Book Dues:");
        home_card.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        main_panel.add(home_card, "profile");
        home_card.getAccessibleContext().setAccessibleName("profile_p");

        getContentPane().add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 890, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 153, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(1030, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(1030, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Librarian Panel");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setRequestFocusEnabled(false);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 890, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    final Color theme = new Color(255,204,102);
    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        main_panel.removeAll();
        main_panel.add(home_card);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_HomeActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void HomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HomeFocusGained
        Home.setBackground(theme);
    }//GEN-LAST:event_HomeFocusGained

    private void HomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HomeFocusLost
        Home.setBackground(Color.white);
    }//GEN-LAST:event_HomeFocusLost

    private void profileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_profileFocusGained
        profile.setBackground(theme);
    }//GEN-LAST:event_profileFocusGained

    private void profileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_profileFocusLost
        profile.setBackground(Color.white);
    }//GEN-LAST:event_profileFocusLost

    private void manage_booksFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manage_booksFocusGained
        manage_books.setBackground(theme);
    }//GEN-LAST:event_manage_booksFocusGained

    private void search_bookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_bookFocusLost
        search_book.setBackground(Color.white);
    }//GEN-LAST:event_search_bookFocusLost

    private void manage_booksFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manage_booksFocusLost
        manage_books.setBackground(Color.white);
    }//GEN-LAST:event_manage_booksFocusLost

    private void return_bookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_return_bookFocusGained
        return_book.setBackground(theme);
    }//GEN-LAST:event_return_bookFocusGained

    private void issue_bookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issue_bookFocusGained
        issue_book.setBackground(theme);
    }//GEN-LAST:event_issue_bookFocusGained

    private void issued_bookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issued_bookFocusGained
        issued_book.setBackground(theme);
    }//GEN-LAST:event_issued_bookFocusGained

    private void aboutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aboutFocusGained
        about.setBackground(theme);
    }//GEN-LAST:event_aboutFocusGained

    private void issued_bookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issued_bookFocusLost
        issued_book.setBackground(Color.white);
    }//GEN-LAST:event_issued_bookFocusLost

    private void aboutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aboutFocusLost
        about.setBackground(Color.white);
    }//GEN-LAST:event_aboutFocusLost

    private void issue_bookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issue_bookFocusLost
        issue_book.setBackground(Color.white);
    }//GEN-LAST:event_issue_bookFocusLost

    private void return_bookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_return_bookFocusLost
        return_book.setBackground(Color.white);
    }//GEN-LAST:event_return_bookFocusLost

    private void search_bookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_bookFocusGained
        search_book.setBackground(theme);
    }//GEN-LAST:event_search_bookFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        main_panel.removeAll();
        main_panel.add(Profile);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        main_panel.removeAll();
        main_panel.add(about_p);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_aboutActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        main_panel.removeAll();
        main_panel.add(Profile);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_profileActionPerformed

    private void manage_booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_booksActionPerformed
        main_panel.removeAll();
        main_panel.add(manage);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_manage_booksActionPerformed

    private void search_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bookActionPerformed
        main_panel.removeAll();
        main_panel.add(SearchBook);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_search_bookActionPerformed

    private void return_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_bookActionPerformed
        main_panel.removeAll();
        main_panel.add(ReturnBook);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_return_bookActionPerformed

    private void issue_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue_bookActionPerformed
        main_panel.removeAll();
        main_panel.add(IssueBook);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_issue_bookActionPerformed

    private void issued_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issued_bookActionPerformed
        main_panel.removeAll();
        main_panel.add(IssuedBook);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_issued_bookActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton Home;
    private javax.swing.JPanel IssueBook;
    private javax.swing.JPanel IssuedBook;
    private javax.swing.JPanel Profile;
    private javax.swing.JPanel ReturnBook;
    private javax.swing.JPanel SearchBook;
    private javax.swing.JButton about;
    private javax.swing.JPanel about_p;
    private javax.swing.JPanel home_card;
    private javax.swing.JLabel icon2;
    private javax.swing.JButton issue_book;
    private javax.swing.JButton issued_book;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel manage;
    private javax.swing.JButton manage_books;
    private javax.swing.JLabel name1;
    private javax.swing.JButton profile;
    private javax.swing.JButton return_book;
    private javax.swing.JButton search_book;
    private javax.swing.JPanel side_menu;
    // End of variables declaration//GEN-END:variables
}
