/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;


import java.util.Date;
import java.awt.Color;
import java.awt.Frame;
import static java.lang.Math.abs;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Duration;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author vimle
 */
public class student_home extends javax.swing.JFrame {
    
    /**
     * Creates new form dashboard
     * @param username
     */
    Connection con;
    PreparedStatement Query;
    String bkid, iss_id, rtbkid, rtiss_id, name;
    final Color theme = new Color(255,204,102);
    LocalDate d = LocalDate.now();
    LocalDate iss_Date = d;
    LocalDate ret_Date = d.plusMonths(1);
    
    public student_home(String username) {
        initComponents();
        name = username;
        name1.setText(username);
        //name2.setText(username);
        getDBConnection();
        dashboardUpdate();
    }

    public student_home() {
        JOptionPane.showMessageDialog(this, "error");
        this.dispose();
    }
    
    private void getDBConnection(){
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/Library_Management","root","0000");
            if(con.isValid(2))
                status.setText("Online");
            else
                status.setText("Offline");
            
        }catch(ClassNotFoundException | SQLException e){ System.out.println(e);}
    }
    
    private void dashboardUpdate(){
        try {
            Query = con.prepareStatement("select count(*) AS total from issuedbooks;");
            PreparedStatement Query1 = con.prepareStatement("select count(*) AS total from books;");
            ResultSet rs1 = Query.executeQuery();
            ResultSet rs2 = Query1.executeQuery();
            if(rs1.next())
                jLabel36.setText(String.valueOf(rs1.getInt("total")));
            if(rs2.next())
                jLabel47.setText(String.valueOf(rs2.getInt("total")));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        side_menu = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        search_book = new javax.swing.JButton();
        issued_book = new javax.swing.JButton();
        about = new javax.swing.JButton();
        Pofile_Panel = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        icon2 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();
        home_card = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        Profile = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        course = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        phno = new javax.swing.JTextField();
        bckgrnd1 = new javax.swing.JLabel();
        SearchBook = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        term = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        IssuedBook = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        about_p = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setIconImage(new ImageIcon(getClass().getResource("/Login_Signup/logo.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_menu.setBackground(new java.awt.Color(255, 255, 255));
        side_menu.setAutoscrolls(true);
        side_menu.setFocusable(false);
        side_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/home.png"))); // NOI18N
        Home.setText("Home");
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.setFocusPainted(false);
        Home.setHideActionText(true);
        Home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home.setIconTextGap(15);
        Home.setMaximumSize(new java.awt.Dimension(200, 50));
        Home.setMinimumSize(new java.awt.Dimension(200, 50));
        Home.setOpaque(true);
        Home.setPreferredSize(new java.awt.Dimension(210, 40));
        Home.setSelected(true);
        Home.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                HomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                HomeFocusLost(evt);
            }
        });
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        side_menu.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 50));

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/profile.png"))); // NOI18N
        profile.setText("Profile");
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        profile.setFocusPainted(false);
        profile.setHideActionText(true);
        profile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profile.setIconTextGap(15);
        profile.setMaximumSize(new java.awt.Dimension(200, 50));
        profile.setMinimumSize(new java.awt.Dimension(200, 50));
        profile.setOpaque(true);
        profile.setPreferredSize(new java.awt.Dimension(210, 40));
        profile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                profileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                profileFocusLost(evt);
            }
        });
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        side_menu.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 50));

        search_book.setBackground(new java.awt.Color(255, 255, 255));
        search_book.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        search_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/search book.png"))); // NOI18N
        search_book.setText("Search Book");
        search_book.setBorderPainted(false);
        search_book.setContentAreaFilled(false);
        search_book.setFocusPainted(false);
        search_book.setHideActionText(true);
        search_book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        search_book.setIconTextGap(15);
        search_book.setMaximumSize(new java.awt.Dimension(200, 50));
        search_book.setMinimumSize(new java.awt.Dimension(200, 50));
        search_book.setOpaque(true);
        search_book.setPreferredSize(new java.awt.Dimension(210, 40));
        search_book.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_bookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search_bookFocusLost(evt);
            }
        });
        search_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_bookActionPerformed(evt);
            }
        });
        side_menu.add(search_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 50));

        issued_book.setBackground(new java.awt.Color(255, 255, 255));
        issued_book.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        issued_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/issued books.png"))); // NOI18N
        issued_book.setText("Issued Books");
        issued_book.setBorderPainted(false);
        issued_book.setContentAreaFilled(false);
        issued_book.setFocusPainted(false);
        issued_book.setHideActionText(true);
        issued_book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        issued_book.setIconTextGap(15);
        issued_book.setMaximumSize(new java.awt.Dimension(200, 50));
        issued_book.setMinimumSize(new java.awt.Dimension(200, 50));
        issued_book.setOpaque(true);
        issued_book.setPreferredSize(new java.awt.Dimension(210, 40));
        issued_book.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                issued_bookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                issued_bookFocusLost(evt);
            }
        });
        issued_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issued_bookActionPerformed(evt);
            }
        });
        side_menu.add(issued_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 50));

        about.setBackground(new java.awt.Color(255, 255, 255));
        about.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/about.png"))); // NOI18N
        about.setText("About");
        about.setBorderPainted(false);
        about.setContentAreaFilled(false);
        about.setFocusPainted(false);
        about.setHideActionText(true);
        about.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        about.setIconTextGap(15);
        about.setMaximumSize(new java.awt.Dimension(200, 50));
        about.setMinimumSize(new java.awt.Dimension(200, 50));
        about.setOpaque(true);
        about.setPreferredSize(new java.awt.Dimension(210, 40));
        about.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aboutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aboutFocusLost(evt);
            }
        });
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        side_menu.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, 50));

        Pofile_Panel.setBackground(new java.awt.Color(255, 153, 0));
        Pofile_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status.setText("Offline");
        Pofile_Panel.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 70, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Pofile_Panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 80));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/user_lx.png"))); // NOI18N
        Pofile_Panel.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 65, -1));

        name1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name1.setText("Vimlesh Kumar");
        Pofile_Panel.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 22, 97, -1));

        side_menu.add(Pofile_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 80));

        getContentPane().add(side_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 640));

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new java.awt.CardLayout());

        home_card.setBackground(new java.awt.Color(255, 255, 255));
        home_card.setPreferredSize(new java.awt.Dimension(890, 600));
        home_card.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel45.setText("Dashboard");
        home_card.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Total Books:");
        home_card.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel15.setText("500");
        home_card.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 90, 60));
        home_card.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 150, 100));
        home_card.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 150, 100));

        jLabel10.setText("Book Dues:");
        home_card.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel36.setText("500");
        home_card.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, 60));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel46.setText("Books Available");
        home_card.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel47.setText("500");
        home_card.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 90, 60));

        jLabel13.setBackground(new java.awt.Color(255, 102, 255));
        jLabel13.setForeground(new java.awt.Color(255, 102, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/Backgnd1.jpg"))); // NOI18N
        home_card.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 600));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel48.setText("Book Issued:");
        home_card.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        main_panel.add(home_card, "profile");
        home_card.getAccessibleContext().setAccessibleName("profile_p");

        Profile.setBackground(new java.awt.Color(255, 255, 255));
        Profile.setMinimumSize(new java.awt.Dimension(890, 600));
        Profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel50.setText("Profile:");
        Profile.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel52.setText("Username");
        Profile.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel53.setText("Name");
        Profile.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel54.setText("Course");
        Profile.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel55.setText("Student ID");
        Profile.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel56.setText("Email Id");
        Profile.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel57.setText("Phone No.");
        Profile.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        fullname.setEditable(false);
        fullname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fullname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Profile.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 220, -1));

        userName.setEditable(false);
        userName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        Profile.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 220, -1));

        course.setEditable(false);
        course.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        course.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        Profile.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 220, -1));

        ID.setEditable(false);
        ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        Profile.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 220, -1));

        mail.setEditable(false);
        mail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Profile.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 220, -1));

        phno.setEditable(false);
        phno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phno.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnoActionPerformed(evt);
            }
        });
        Profile.add(phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 220, -1));

        bckgrnd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/boy.png"))); // NOI18N
        Profile.add(bckgrnd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 230, 240));

        main_panel.add(Profile, "card4");

        SearchBook.setBackground(new java.awt.Color(255, 255, 255));
        SearchBook.setMinimumSize(new java.awt.Dimension(890, 600));
        SearchBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(153, 255, 153));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Search By:");
        SearchBook.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 60, 30));

        term.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        term.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        term.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termActionPerformed(evt);
            }
        });
        SearchBook.add(term, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 280, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Search");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        SearchBook.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, 30));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel43.setText("Search Book");
        SearchBook.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book ID", "Title", "Edition", "Author", "Publisher", "ISBN", "Subject" }));
        SearchBook.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 110, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Title", "Author", "Publisher", "Edition", "ISBN", "Subject", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        SearchBook.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 830, 450));

        main_panel.add(SearchBook, "card4");

        IssuedBook.setBackground(new java.awt.Color(255, 255, 255));
        IssuedBook.setMinimumSize(new java.awt.Dimension(890, 600));
        IssuedBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Student Id", "Issue Date", "Return Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        IssuedBook.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 820, 520));

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("Issued Books");
        IssuedBook.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/go.png"))); // NOI18N
        jButton11.setContentAreaFilled(false);
        jButton11.setOpaque(true);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        IssuedBook.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, 40));

        main_panel.add(IssuedBook, "card3");

        about_p.setBackground(new java.awt.Color(255, 255, 255));
        about_p.setMinimumSize(new java.awt.Dimension(890, 600));
        about_p.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Library Management ");
        about_p.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("System");
        about_p.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Developed By:");
        about_p.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel5.setText("Vimlesh Kumar");
        about_p.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 130, -1));

        jLabel6.setText("Umesh Maharwaha");
        about_p.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel7.setText("Sajid Khalloo");
        about_p.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Beta version");
        about_p.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, 20));

        main_panel.add(about_p, "about");

        getContentPane().add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 890, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 153, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(1030, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(1030, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Panel");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setRequestFocusEnabled(false);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(204, 0, 51));
        jButton3.setText("Logout");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 890, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        main_panel.removeAll();
        main_panel.add(home_card);
        main_panel.repaint();
        main_panel.revalidate();
        dashboardUpdate();
    }//GEN-LAST:event_HomeActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void HomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HomeFocusGained
        Home.setBackground(theme);
    }//GEN-LAST:event_HomeFocusGained

    private void HomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HomeFocusLost
        Home.setBackground(Color.white);
    }//GEN-LAST:event_HomeFocusLost

    private void profileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_profileFocusGained
        profile.setBackground(theme);
    }//GEN-LAST:event_profileFocusGained

    private void profileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_profileFocusLost
        profile.setBackground(Color.white);
    }//GEN-LAST:event_profileFocusLost

    private void search_bookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_bookFocusLost
        search_book.setBackground(Color.white);
    }//GEN-LAST:event_search_bookFocusLost

    private void issued_bookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issued_bookFocusGained
        issued_book.setBackground(theme);
    }//GEN-LAST:event_issued_bookFocusGained

    private void aboutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aboutFocusGained
        about.setBackground(theme);
    }//GEN-LAST:event_aboutFocusGained

    private void issued_bookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issued_bookFocusLost
        issued_book.setBackground(Color.white);
    }//GEN-LAST:event_issued_bookFocusLost

    private void aboutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aboutFocusLost
        about.setBackground(Color.white);
    }//GEN-LAST:event_aboutFocusLost

    private void search_bookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_bookFocusGained
        search_book.setBackground(theme);
    }//GEN-LAST:event_search_bookFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        main_panel.removeAll();
        main_panel.add(Profile);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        main_panel.removeAll();
        main_panel.add(about_p);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_aboutActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        main_panel.removeAll();
        main_panel.add(Profile);
        main_panel.repaint();
        main_panel.revalidate();
        try {
            Query = con.prepareStatement("select * from students, users where students.ID = users.ID and username = ?;");
            Query.setString(1, name);
            System.out.println(Query);
            ResultSet rs = Query.executeQuery();
            if(rs.next()){
                fullname.setText(rs.getString("Name"));
                userName.setText(rs.getString("username"));
                course.setText(rs.getString("Course"));
                mail.setText(rs.getString("Email"));
                ID.setText(rs.getString("ID"));
                phno.setText(rs.getString("Phone_No"));
            }
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_profileActionPerformed

    private void search_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bookActionPerformed
        main_panel.removeAll();
        main_panel.add(SearchBook);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_search_bookActionPerformed

    private void issued_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issued_bookActionPerformed
        main_panel.removeAll();
        main_panel.add(IssuedBook);
        main_panel.repaint();
        main_panel.revalidate();
        try {
            Query = con.prepareStatement("select * from IssuedBooks where ID = ?;");
            Query.setString(1, this.name);
            ResultSet rs = Query.executeQuery();
            
            DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            int count = m.getRowCount()-1;
            while(count>=0){
                m.removeRow(count--);
            }
            while(rs.next())
                m.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_issued_bookActionPerformed

    private void termActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termActionPerformed
        
    }//GEN-LAST:event_termActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {                                         
            
            switch(jComboBox1.getSelectedIndex()){
                case 0:
                    Query = con.prepareStatement("select * from books where BookID LIKE ?;");
                    break;
                case 1:
                    Query = con.prepareStatement("select * from books where Title LIKE ?;");
                    break;
                case 2:
                    Query = con.prepareStatement("select * from books where Author LIKE ?;");
                    break;
                case 3:
                    Query = con.prepareStatement("select * from books where Publisher LIKE ?;");
                    break;
                case 4:
                    Query = con.prepareStatement("select * from books where Edition LIKE ?;");
                    break;
                case 5:
                    Query = con.prepareStatement("select * from books where ISBN LIKE ?;");
                    break;
                case 6:
                    Query = con.prepareStatement("select * from books where Subject LIKE ?;");
                    break;
            }
            String k = term.getText();
                        Query.setString(1,"%"+k+"%");
                        System.out.print(Query);
                        ResultSet rs = Query.executeQuery();
                        DefaultTableModel m = (DefaultTableModel) jTable2.getModel();
                        int count = m.getRowCount()-1;
                        while(count>=0){
                            m.removeRow(count--);
                        }
                            while(rs.next())
                                m.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4),
                                    rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getInt(9)});
                        
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            Query = con.prepareStatement("select * from IssuedBooks where ID = ?;");
            Query.setString(1, this.name);
            System.out.println(Query);
            ResultSet rs = Query.executeQuery();
            DefaultTableModel m = (DefaultTableModel) jTable2.getModel();
            int count = m.getRowCount()-1;
            while(count>=0){
                m.removeRow(count--);
            }
            while(rs.next())
                m.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void phnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnoActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
         new Login_Signup.Login().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton Home;
    private javax.swing.JTextField ID;
    private javax.swing.JPanel IssuedBook;
    private javax.swing.JPanel Pofile_Panel;
    private javax.swing.JPanel Profile;
    private javax.swing.JPanel SearchBook;
    private javax.swing.JButton about;
    private javax.swing.JPanel about_p;
    private javax.swing.JLabel bckgrnd1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField course;
    private javax.swing.JTextField fullname;
    private javax.swing.JPanel home_card;
    private javax.swing.JLabel icon2;
    private javax.swing.JButton issued_book;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField mail;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel name1;
    private javax.swing.JTextField phno;
    private javax.swing.JButton profile;
    private javax.swing.JButton search_book;
    private javax.swing.JPanel side_menu;
    private javax.swing.JLabel status;
    private javax.swing.JTextField term;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
